// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqctsbahpxeosufvapln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxY3RzYmFocHhlb3N1ZnZhcGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzg5NTMsImV4cCI6MjA2OTYxNDk1M30.Py39F1-_Z8-QusK2IQsoH-ZCrRxEaoP0OCmTpyx3_3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});